
[project]
name = "triangle-example"
authors = ["DevTaube"]
version = "0.1.0"
# main class name (needs to extends 'rosequartz.Project' (base API))
main_class = "rosequartz.example.triangle.Main"
# jvm arguments
vmargs = "-Xmx2G"

[config-general]
# fps cap, 0 = no fps limit
target_fps = 0
# enable rosequartz console (toggled with F3)
console = false

[config-graphics]
# icon for your game to use (inside 'res'-directory)
icon = ""
# sync monitor refresh rate with game frame rate
vsync = false

[config-graphics-desktop] # game window configuration
width = 848
height = 480
resizable = true
fullscreen = true
